services:
  back:
    image: chialab/php:8.0-fpm
    restart: always
    volumes:
      - ./${ROOT}:/var/www/html
    environment:
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpwd
      MYSQL_DATABASE: dbdev

  db:
    image: mariadb:10
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpwd
      MYSQL_DATABASE: dbdev

  dbadmin:
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpwd
